# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - GNG-5300-week-9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a42f733555e54743b265c63a6cc22c81 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_090f503c013a4bbc8fcb24d92c3e571d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/locajk/nextjs-fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GNG-5300-week-9'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7d31a5930f0c4c799a754909dfc72c0e }}
        images: 'index.docker.io/locajk/nextjs-fastapi:${{ github.sha }}'
