# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - GNG-5300-week-9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_efed3c170c6a4a2a944eda9cf03a6ac5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0eae1226946e4aa5b91e4dd7c83f7346 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_efed3c170c6a4a2a944eda9cf03a6ac5 }}/locojk/nextjs-fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GNG-5300-week-9'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_335d2f42c0574418b40b3f4dc84776aa }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_efed3c170c6a4a2a944eda9cf03a6ac5 }}/locojk/nextjs-fastapi:${{ github.sha }}'